name: Deploy Website

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codemain  # Change this to the branch you want to deploy from
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build project
      run: |
        # Add your build commands here
        # Example for a Node.js project
        npm install
        npm run build

    - name: Deploy to Server
      env:
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        scp -r ./build/* $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
